### ISSUE TITLE
Error when using socket.io v3

### ISSUE THREAD

**Issue by paivaric** [darrachequesne/socket.io-json-parser#4]
```
TypeError: callback is not a function
    at Encoder.encode (node_modules/socket.io-json-parser/index.js:27:10)
    at Client._packet (node_modules/socket.io/dist/client.js:169:44)
    at Socket.packet (node_modules/socket.io/dist/socket.js:165:21)
    at Socket._onconnect (node_modules/socket.io/dist/socket.js:209:18)
    at /Users/paiva/dev/econdos/econdos-backend/node_modules/socket.io/dist/namespace.js:130:28
    at processTicksAndRejections (internal/process/task_queues.js:79:11)

```

**Comment by darrachequesne** [comment]
This should be fixed by https://github.com/darrachequesne/socket.io-json-parser/commit/e7223ac84d563fc35de27bfef3b9b6fdb1c6db98, included in `socket.io-json-parser@3.0.0`.
